### PR TITLE
Fix desktop entry

### PR DESCRIPTION
**Pull request by TheAssassin**
The current desktop file contains one error (`Categories` is supposed to be a list, and all entries must be terminated by a semicolon), and one annoyance (the path in `Exec` doesn't have to be absolute). This PR fixes both issues.

### CODE REVIEW

**Comment by TheAssassin** [comment]
By the way, you can use `desktop-file-validate` to check your desktop entries for errors.

**Comment by ids1024** [comment]
> By the way, you can use desktop-file-validate to check your desktop entries for errors.

Hm, I ran that when I submited Popsicle to Flathub, since that's something they said to do for new packages. It doesn't seem to be returning any errors without this change?

The `Makefile` has a `sed` call adjusting the `Exec` path depending on where it is installed. So I suppose if we're using an absolute path, that should be removed as well. Otherwise, not relying on an absolute path is great, as long as there wasn't some good reason it was done that way.

**Comment by ids1024** [comment]
It looks like the `.desktop` file has been using an absolute path since it was added in 1c86da3f5cf9d0dc76e57e319e1904022dce2d83.

@mmstick Do you foresee any issues with changing this to just `Exec=popsicle-gtk %f`?

**Comment by mmstick** [comment]
No issues. I've just had the makefile convert it to the correct absolute path during install

**Comment by ids1024** [comment]
@TheAssassin if you update the PR to also remove the now unneeded `sed` call in the `Makefile`, I think this should be good to merge.

**Review by ids1024 — CHANGES_REQUESTED** [review]
Requires a `Makefile` change, as noted already.

**Comment by TheAssassin** [comment]
Done.

**Review by ids1024 — APPROVED** [review]

**Review by leviport — APPROVED** [review]

**Pull request merged**
