### PR TITLE
GitHub Actions: Add Flatpak action

### PR DESCRIPTION
**Pull request by cassidyjames**
This adds a GitHub Actions workflow to test the Flatpak build; this can ensure future changes don't break the Flatpak build. Requires a Flatpak manifest, e.g. from #187

### CODE REVIEW

**Comment by jackpot51** [comment]
I will wait for #187 to be merged before reviewing this.

**Comment by jackpot51** [comment]
Now that #187 is merged, please rebase this so it is one commit on top of master. It should pass CI after that.

**Comment by cassidyjames** [comment]
I see another issue raised by CI that I've resolved in #189

**Comment by jacobgkau** [comment]
Looks like this is still failing.
```
 Starting build of com.system76.Popsicle
========================================================================
Building module popsicle in /__w/popsicle/popsicle/.flatpak-builder/build/popsicle-1
========================================================================
Running: make
make: *** No targets specified and no makefile found.  Stop.
Error: module popsicle: Child process exited with code 2
Error: Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```

**Comment by ids1024** [comment]
https://github.com/flathub/com.system76.Popsicle is updated to the latest release now.

`generated-sources.json` is generated using https://github.com/flatpak/flatpak-builder-tools/blob/master/cargo/flatpak-cargo-generator.py.

**Pull request closed without merging**
