### PR TITLE
i18n(bn): Translation Bangla

### PR DESCRIPTION
**Pull request by Oymate**
Please review

### CODE REVIEW

**Comment by mmstick** [comment]
Needs a translation for popsicle_cli.ftl too

**Comment by Oymate** [comment]
I am not sure if CLI translation is of any use since, the terminal doesn't have complex text layout 
https://en.wikipedia.org/wiki/Complex_text_layout

**Comment by mmstick** [comment]
Whether it's complex or not, people will appreciate having instructions written in their language, otherwise they'd have to be very comfortable with English.

**Comment by Oymate** [comment]
OK, but for a reference in English it looks like this:
https://filestore.community.support.microsoft.com/api/images/e229833f-7089-4c3f-9c18-f04f0a13bd8b

**Comment by Oymate** [comment]
Can I translate 'y/n' ?

**Comment by Oymate** [comment]
Done!

**Pull request merged**
