### PR TITLE
Fix potential early exit with CLI

### LINKED ISSUE #85: Rendered usb media not working using CLI version
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Package files:
 100 /var/lib/dpkg/status
     release a=now
1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
     release v=19.10,o=LP-PPA-system76-pop,a=eoan,n=eoan,l=Pop!_OS PPA,c=main,b=i386
     origin ppa.launchpad.net
1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
     release v=19.10,o=LP-PPA-system76-pop,a=eoan,n=eoan,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/mmstick76/ion-shell/ubuntu eoan/main i386 Packages
     release v=19.10,o=LP-PPA-mmstick76-ion-shell,a=eoan,n=eoan,l=ion-shell,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/mmstick76/ion-shell/ubuntu eoan/main amd64 Packages
     release v=19.10,o=LP-PPA-mmstick76-ion-shell,a=eoan,n=eoan,l=ion-shell,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/fontforge/fontforge/ubuntu eoan/main i386 Packages
     release v=19.10,o=LP-PPA-fontforge-fontforge,a=eoan,n=eoan,l=FontForge,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/fontforge/fontforge/ubuntu eoan/main amd64 Packages
     release v=19.10,o=LP-PPA-fontforge-fontforge,a=eoan,n=eoan,l=FontForge,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/agornostal/ulauncher/ubuntu eoan/main i386 Packages
     release v=19.10,o=LP-PPA-agornostal-ulauncher,a=eoan,n=eoan,l=Ulauncher,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/agornostal/ulauncher/ubuntu eoan/main amd64 Packages
     release v=19.10,o=LP-PPA-agornostal-ulauncher,a=eoan,n=eoan,l=Ulauncher,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://apt.pop-os.org/proprietary eoan/main all Packages
     release v=19.10,o=system76,a=eoan,n=eoan,l=System76,c=main,b=all
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary eoan/main amd64 Packages
     release v=19.10,o=system76,a=eoan,n=eoan,l=System76,c=main,b=amd64
     origin apt.pop-os.org
 100 http://us.archive.ubuntu.com/ubuntu eoan-backports/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-backports,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu eoan-backports/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-backports,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/multiverse i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/multiverse amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/restricted amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/multiverse i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/multiverse amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/restricted amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/main i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/main amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/multiverse i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/multiverse amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/restricted i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/restricted amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/main i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
Pinned packages:

**Issue/Bug Description:**

I tried to use popsicle cli (using i3) to put the latest 19.10 iso (intel) on
a usb stick. Everything went right during the process except that the rendered
usb stick was not usable at all. I was able to boot from it in the BIOS but 
then I had an empty prompt with an infinite blancking underscore character.

The file structure on the usb key looks okay so I have no idea what's going on.
I did not used the check option (I never test my iso files, I know I'm bad :)).
When I switched back to the pop session however I used the GUI version, same 
settings etc... and I was able to get a proper working usb stick using the 
exact same iso.

I'm glad you guys provide us some nice tools (CLI and GUI) and I hope that 
those infos could help to solve the issue...

**Steps to reproduce (if you know):**

Simply grab the latest intel iso and type in a shell $ popsicle /path/to/the/iso /path/to/the/usb/device
Wait until the shell prompt ask for new commands.
Reboot on the usb stick.
You're there!

### PR DESCRIPTION
**Pull request by mmstick**
Closes #85

### CODE REVIEW

**Comment by brs17** [comment]
@7FFY could you please take a look at see if this issue persists with this added patch? I was able to test to make sure it doesn't seem to break anything but I was unable to replicate your issue to begin with. You can either build it from source or:

```
git clone https://github.com/pop-os/pop
./pop/scripts/apt add cli-fix
sudo apt update
sudo apt full-upgrade
```

**Comment by 7FFY** [comment]
@brs17 Np, gonna do this tomorrow however

**Comment by 7FFY** [comment]
Hi, so I tested the patched version but the issue persist :/

**Comment by mmstick** [comment]
Sadly, I haven't been able to replicate the issue, either. So this will take more digging for a potential cause.

**Pull request closed without merging**
