### PR TITLE
Wayland Support

### LINKED ISSUE #16: Run GUI as normal user
This places popsicle in the right context to allow them to browse for an ISO. Upon flashing, launch a command line executable with pkexec and use a pipe to read the status for each drive back into the GUI.

### PR DESCRIPTION
**Pull request by mmstick**
- Background threads will be created which will run authenticated tasks.
- The main thread will use Linux syscalls to downgrade permissions.
- A channel will be used to request information from the authenticated threads.

This _may_ fix the issue of launching Popsicle on a Wayland session. The main thread will initially spawn as root via pkexec or sudo, and will spawn background threads that will remain as root to perform authenticated tasks in the background. After spawning the background threads, permissions are downgraded back to a normal user before initializing GTK, and the UI will run entirely as a normal user.

Fixes #16

### CODE REVIEW

**Comment by mmstick** [comment]
@brs17 Does this fix Wayland compatibility?

**Comment by brs17** [comment]
It looks like in a Wayland session one can launch popsicle now!

**Comment by mmstick** [comment]
I'll merge it as soon as I can.

**Comment by brs17** [comment]
Although you may want a code review (I just ran it to see if it would work)

**Comment by mmstick** [comment]
@jackpot51 Would you like to review this?

**Pull request merged**
