### PR TITLE
Disallow selecting a device that is too small

### LINKED ISSUE #46: Writing image bigger than USB
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
popsicle:
  Installed: 0.1.5~1526005323~18.04~9254724
  Candidate: 0.1.5~1526005323~18.04~9254724
  Version table:
 *** 0.1.5~1526005323~18.04~9254724 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Popsicle allows writing a bigger image than the capacity of the USB without warning the user.

**Expected behavior:**
A prompt should appear saying that this operation cannot be done since the size of the image is bigger than the USB.

### PR DESCRIPTION
**Pull request by mmstick**
Fixes #46 

The selected ISO is 2.3 GB, whereas `/dev/sdd` is a 2GB flash drive.

screenshot from 2018-06-20 12-33-33

### CODE REVIEW

**Comment by brs17** [comment]
Below are some screenshots from trying this patch out.

Looks like you can still attempt to write to a drive that is too small. I do not think that should be allowed.

screenshot from 2018-06-26 09-28-58

screenshot from 2018-06-26 09-29-09

screenshot from 2018-06-26 09-36-46

**Comment by isantop** [comment]
There may be cases where that would be desireable behavior. For example, if someone is trying to flash an image taken of a large, mostly empty disk, You would want to be able to write the mostly empty image to a smaller drive. 

That's something of a niche case, but it is one that exists.

**Comment by cassidyjames** [comment]
@isantop that's enough of an edge case plus new feature that I'm gonna recommend we ignore it in the context of this PR. :stuck_out_tongue: The write still fails in this case.

@brs17 It looks like selecting the "all" checkbox still selects the disabled items?

**Comment by brs17** [comment]
That was the case @cassidyjames, `Select All` selects the drive that is too small.

I agree with @cassidyjames that in the context of this pr, we should leave out a new feature to cover an edge case.

**Comment by mmstick** [comment]
1 line of code should fix the select all button.

**Comment by brs17** [comment]
Related, `Select all` can be selected when there are no drives connected at all. I guess technically something that warrants a new issue but both can probably be fixed at once since these are both cases of "no drive large enough is connected"

**Comment by mmstick** [comment]
@brs17 I can fix that with another one-liner.

**Comment by mmstick** [comment]
@brs17 It should be fixed now. Found another issue as I was testing on my end. A device can be registered as 'too small' when its size is read too early. It's now handling that error by attempting to re-attain the device size for up to 10 seconds.

**Pull request merged**
