### PR TITLE
GTK App Fixes

### LINKED ISSUE #18: Local build instructions
It would be useful to add local development and building instructions to the README so others can contribute.

### LINKED ISSUE #19: "Select all" checkbox should be bound to the selection state of the drives
1. If I uncheck "Select all", it should deselect all drives
2. If I uncheck a drive in the list, "Select all" should switch to the mixed state (`inconsistent` property)

From the GNOME HIG: https://developer.gnome.org/hig/stable/check-boxes.html.en#guidelines

>If the check box represents a setting in a multiple selection that is set for some objects in the selection and unset for others, show the check box in its mixed state. When a check box is in its mixed state:
>
>- Clicking the box once should check the box, applying that setting (when confirmed) to all the selected objects.
>
>- Clicking the box a second time should uncheck the box, removing that setting (when confirmed) to all the selected objects.
>
>- Clicking the box a third time should return the box to its mixed state, restoring each selected object’s original value for that setting (when confirmed).

### LINKED ISSUE #20: .back → .back-button class
My bad in the spec. The proper class is `.back-button`, not `.back` to add a back arrow to the button. As a note, this class should only be present on the devices page (when the button says, "Back"). Otherwise, it's just a normal button.

### LINKED ISSUE #21: Add "Hash:" label before the hash combobox
It's not immediately clear what "Type" means, which is why we should label the widget. See the design spec: https://github.com/pop-os/popsicle/wiki/GUI-Design#choose-an-image

### LINKED ISSUE #23: Move spacing from CSS to properties
Any time we're using padding or margin in CSS, we should probably move to setting the margin properties on the widgets themselves instead. This makes it much easier to prototype and use the GTK inspector.

### LINKED ISSUE #24: Remove borders on drive selection
We should remove the borders in CSS, and rely on a GtkSeparator in the list to separate "Select all" from the drives.

### LINKED ISSUE #25: Improve margins for chooser_container
Set margins to top: 12, bottom: 24

### LINKED ISSUE #26: Add margins to stack
Add a 12px margin to the stack to give a little breathing room.

### PR DESCRIPTION
**Pull request by mmstick**
This PR will work to address all open issues regarding the GTK front end, and then some, with additional abstraction work to minimize the GTK work.

- [x] Closes #18 
- [x] Closes #19 
- [x] Closes #20 
- [x] Closes #21
- [x] Closes #23 
- [x] Closes #24 
- [x] Closes #25 
- [x] Closes #26

### CODE REVIEW

**Comment by jackpot51** [comment]
I think at line 314 in `gtk/src/app/state.rs`, the device list is not filtered based on the checkbutton. Is that true?

**Comment by jackpot51** [comment]
The hash gets truncated now that that `Hash:` label is before the dropdown. Perhaps we should increase the minimum size of the window?

**Comment by mmstick** [comment]
Yeah, it should default to a size that fits the complete hash.

**Comment by jackpot51** [comment]
Should the minimum size also be set?

**Comment by mmstick** [comment]
Unsure on how to set a minimum size at the moment.

**Comment by jackpot51** [comment]
That's ok, I think it is fine as-is

**Comment by jackpot51** [comment]
Since this is an improvement over how it was before, I will merge so it makes it into the next ISO. Further issues may be filed concerning the master branch

**Pull request merged**
