### PR TITLE
i18n(tr): Add Turkish translation

### PR DESCRIPTION
**Pull request by alpkaanaksu**

### CODE REVIEW

**Comment by jacobgkau** [comment]
Thank you for the translation! Comparing with the English copy, I am curious why you removed the periods (full stops) at the end of most of the sentences in the second commit. Just to confirm, is there a grammatical reason for that? (I tried to look this up, but the examples of Turkish sentences that I found included periods at the end.)

**Comment by alpkaanaksu** [comment]
Hey @jacobgkau, I removed them to make it similar to the English version. The first time I did it, I just added periods out of habit and while I was checking once more to make sure everything looks fine, I realized that the English original didn't have periods. I have just had a second look at it now and saw that a few of the sentences had periods. I will update my translations accordingly. (I'll add periods whenever they are needed.) Thanks for pointing this out.

**Comment by alpkaanaksu** [comment]
I added periods to the end of sentences. I also capitalized sentences. Sentences look more "complete" now.

**Review by jacobgkau — APPROVED** [review]
Thanks again! (We could probably benefit from making some of the original English sentences more "complete" sometime, too, but things are more consistent now.)

**Review by ids1024 — APPROVED** [review]

**Pull request merged**
